// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4bRawaXr0Enh68rmNmAyr73dxWVYQ95Y',
    appId: '1:235448316706:web:3560d0576b9c8d53abeb7b',
    messagingSenderId: '235448316706',
    projectId: 'ishipetpals',
    authDomain: 'ishipetpals.firebaseapp.com',
    storageBucket: 'ishipetpals.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqSOc-3WGjhoap-dQ_l95Q0jlKuVAASq4',
    appId: '1:235448316706:android:48db6f228c330740abeb7b',
    messagingSenderId: '235448316706',
    projectId: 'ishipetpals',
    storageBucket: 'ishipetpals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6wSbKZK7FViUct7kGt-wLAyls0Zm1ko',
    appId: '1:235448316706:ios:5a404f0dfc2c7ea0abeb7b',
    messagingSenderId: '235448316706',
    projectId: 'ishipetpals',
    storageBucket: 'ishipetpals.firebasestorage.app',
    iosBundleId: 'com.example.petDiceaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD6wSbKZK7FViUct7kGt-wLAyls0Zm1ko',
    appId: '1:235448316706:ios:5a404f0dfc2c7ea0abeb7b',
    messagingSenderId: '235448316706',
    projectId: 'ishipetpals',
    storageBucket: 'ishipetpals.firebasestorage.app',
    iosBundleId: 'com.example.petDiceaseDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4bRawaXr0Enh68rmNmAyr73dxWVYQ95Y',
    appId: '1:235448316706:web:7c42dd9d445fe717abeb7b',
    messagingSenderId: '235448316706',
    projectId: 'ishipetpals',
    authDomain: 'ishipetpals.firebaseapp.com',
    storageBucket: 'ishipetpals.firebasestorage.app',
  );
}
